### ISSUE TITLE
warn

### ISSUE THREAD

**Issue by NNNNelson** [ShouChenICU/WebCamera#11]
![image](https://github.com/ShouChenICU/WebCamera/assets/128298843/10929b89-0d25-4eb4-9675-8502c7047f7f)
能看一下这个问题怎么解决吗

**Comment by ShouChenICU** [comment]
> ![image](https://github.com/ShouChenICU/WebCamera/assets/128298843/10929b89-0d25-4eb4-9675-8502c7047f7f)
> 能看一下这个问题怎么解决吗

Windows的吗，用的node版本是什么

**Comment by NNNNelson** [comment]
是windows 的 node 版本为 v20.14.0
然后在yarn init  的时候有一些依赖包没有安装成功
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning "@nuxt/ui > nuxt-icon > @nuxt/devtools-kit@1.3.1" has unmet peer dependency "vite@*".
warning "@nuxtjs/i18n > @miyaneee/rollup-plugin-json5@1.2.0" has unmet peer dependency "rollup@^1.20.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit@1.3.1" has unmet peer dependency "@nuxt/devtools@1.3.1".
warning "@nuxtjs/seo > @nuxtjs/sitemap > h3-compression@0.3.2" has unmet peer dependency "h3@^1.6.0".
warning "@nuxtjs/seo > nuxt-schema-org > @unhead/schema-org@1.9.11" has unmet peer dependency "unhead@>=1.9.10".
warning "@nuxtjs/seo > nuxt-schema-org > @unhead/schema-org@1.9.11" has unmet peer dependency "@unhead/shared@1.9.11".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > v-lazy-show@0.2.4" has unmet peer dependency "@vue/compiler-core@^3.3".
warning "@nuxtjs/seo > nuxt-og-image > vanilla-jsoneditor > @codemirror/autocomplete@6.16.0" has unmet peer dependency "@lezer/common@^1.0.0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > @unocss/nuxt > @unocss/vite@0.60.3" has unmet peer dependency "vite@^2.9.0 || ^3.0.0-0 || ^4.0.0 || ^5.0.0-0".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > @unocss/nuxt > @unocss/webpack@0.60.3" has unmet peer dependency "webpack@^4 || ^5".
warning "@nuxtjs/seo > @nuxtjs/sitemap > @nuxt/devtools-ui-kit > unocss > @unocss/postcss@0.60.3" has unmet peer dependency "postcss@^8.4.21".
warning "@vite-pwa/nuxt > vite-plugin-pwa@0.20.0" has unmet peer dependency "vite@^3.1.0 || ^4.0.0 || ^5.0.0".
warning "@vite-pwa/nuxt > vite-plugin-pwa@0.20.0" has unmet peer dependency "workbox-build@^7.1.0".
warning "@vite-pwa/nuxt > vite-plugin-pwa@0.20.0" has unmet peer dependency "workbox-window@^7.1.0".
warning "nuxt > @nuxt/devtools@1.3.1" has unmet peer dependency "vite@*".
warning "nuxt > @nuxt/devtools > vite-plugin-inspect@0.8.4" has unmet peer dependency "vite@^3.1.0 || ^4.0.0 || ^5.0.0-0".
warning "nuxt > @nuxt/devtools > vite-plugin-vue-inspector@5.1.2" has unmet peer dependency "vite@^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0".
warning "nuxt > @nuxt/devtools > @vue/devtools-applet > @vue/devtools-ui@7.2.1" has unmet peer dependency "@unocss/reset@>=0.50.0-0".
warning "nuxt > @nuxt/devtools > @vue/devtools-applet > @vue/devtools-ui@7.2.1" has unmet peer dependency "floating-vue@>=2.0.0-0".
warning "nuxt > @nuxt/devtools > @vue/devtools-applet > @vue/devtools-ui@7.2.1" has unmet peer dependency "unocss@>=0.50.0-0".
warning "nuxt > @nuxt/devtools > @vue/devtools-core > vite-hot-client@0.2.3" has unmet peer dependency "vite@^2.6.0 || ^3.0.0 || ^4.0.0 || ^5.0.0-0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/core@1.24.1" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer@0.50.0" has unmet peer dependency "@opentelemetry/api@>=1.3.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/resources@1.24.1" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/sdk-trace-base@1.24.1" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer > @opentelemetry/core@1.23.0" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer > @opentelemetry/resources@1.23.0" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer > @opentelemetry/sdk-logs@0.50.0" has unmet peer dependency "@opentelemetry/api@>=1.4.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer > @opentelemetry/sdk-metrics@1.23.0" has unmet peer dependency "@opentelemetry/api@>=1.3.0 <1.9.0".
warning "nuxt > nitropack > @netlify/functions > @netlify/serverless-functions-api > @opentelemetry/otlp-transformer > @opentelemetry/sdk-trace-base@1.23.0" has unmet peer dependency "@opentelemetry/api@>=1.0.0 <1.9.0".
[4/4] Building fresh packages...
$ nuxt prepare

 WARN  Slow module nuxtseo took 9249.88ms to setup.                                                                                                                                                                                23:12:34

i Using default Tailwind CSS file                                                                                                                                                                                 nuxt:tailwindcss 23:12:37

**Comment by ShouChenICU** [comment]
看起来是某个依赖里的路径引用问题，用我打包好的release试试呢
