### ISSUE TITLE
是否可以支持多人视频？

### ISSUE THREAD

**Issue by liguobao** [ShouChenICU/WebCamera#3]
感觉这个更有意思。

**Comment by ShouChenICU** [comment]
该项目主要做单向视频流监控，后续或许可以开新坑做多人视频

**Comment by liguobao** [comment]
基于当前版本做多人视频的话，这个项目更有意思呀。

**Comment by ShouChenICU** [comment]
> 基于当前版本做多人视频的话，这个项目更有意思呀。

一个产品做好一件事即可，这个项目的定位就是单向的监控，并不是社交相关的产品。
并且多人视频会导致项目复杂度明显提升，也需要更多的时间精力投入开发，考虑各种细节，最后很容易做出4不像的东西出来，一个产品要有它的精准定位才能持续发展，我是这么想的

**Comment by liguobao** [comment]
这点我同意～



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 不神秘的神秘人 ***@***.***&gt;
发送时间: 2024年6月7日 17:03
收件人: ShouChenICU/WebCamera ***@***.***&gt;
抄送: 李国宝 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ShouChenICU/WebCamera] 是否可以支持多人视频？ (Issue #3)





  
基于当前版本做多人视频的话，这个项目更有意思呀。
  
一个产品做好一件事即可，这个项目的定位就是单向的监控，并不是社交相关的产品。
 并且多人视频会导致项目复杂度明显提升，也需要更多的时间精力投入开发，考虑各种细节，最后很容易做出4不像的东西出来，一个产品要有它的精准定位才能持续发展，我是这么想的
