### ISSUE TITLE
感觉严格意义上来讲，这个算是视频通话？不算监控

### ISSUE THREAD

**Issue by zhangjh** [ShouChenICU/WebCamera#6]
试着部署了一下，需要两端同时在线发起，不能一端发起，另一端再随时接入。更像是视频通话，无法满足监控的需求场景。这样的话可能微信更方便一点。。

**Comment by ShouChenICU** [comment]
> 试着部署了一下，需要两端同时在线发起，不能一端发起，另一端再随时接入。更像是视频通话，无法满足监控的需求场景。这样的话可能微信更方便一点。。

摄像头端可以勾选自动重连，会保持在线状态，另一端就可以随时接入了
