### ISSUE TITLE
windows 11 pc camera connecting

### ISSUE THREAD

**Issue by wanghaisheng** [ShouChenICU/WebCamera#8]
![image](https://github.com/ShouChenICU/WebCamera/assets/2363295/e7cabf94-5be8-4ae5-939d-666b1c6d16c2)
疯狂打转 但没有显示连接成功

**Comment by ShouChenICU** [comment]
> ![image](https://github.com/ShouChenICU/WebCamera/assets/2363295/e7cabf94-5be8-4ae5-939d-666b1c6d16c2)
> 疯狂打转 但没有显示连接成功
> 

你需要打开两个页面，或者两个设备，一个作为摄像头连接，另一个作为监控连接，作为监控的连接id要和摄像头的连接id一致

**Comment by wanghaisheng** [comment]
@ShouChenICU 我理解的是 两个设备不是同时打开把
应该是扮演server的先启动，拿到id，分享给别人，别人打开访问页面，通过id连接

我这个只是尝试了先启动服务器

**Comment by ShouChenICU** [comment]
> @ShouChenICU 我理解的是 两个设备不是同时打开把
> 应该是扮演server的先启动，拿到id，分享给别人，别人打开访问页面，通过id连接
> 
> 我这个只是尝试了先启动服务器

是的，作为服务端的先启动，这里是摄像头先启动，ID是预先设置的，这样方便自定义
然后我设计的是用闲置手机当摄像头，自己就能在其他地方看监控了，分享给其他人是有隐私泄露风险的

**Comment by LxzBUG** [comment]
我用小米手机或者苹果手机 safari 作为摄像头都连接不上呢，先点的摄像头作为视频源。

**Comment by ShouChenICU** [comment]
> 我用小米手机或者苹果手机 safari 作为摄像头都连接不上呢，先点的摄像头作为视频源。

也可能是连的人太多了，服务器负载有点大，多刷新试试呢
